doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
          enum: string
          bit: boolean

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    default_entity_manager: default
    entity_managers:
      auto_generate_proxy_classes: true
      auto_mapping: true
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          App\Evaluation\Domain\Entity:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Evaluation/Domain/Entity'
            prefix: 'App\Evaluation\Domain\Entity'
          App\Evaluation\Domain\ValueObject:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Evaluation/Domain/ValueObject'
            prefix: 'App\Evaluation\Domain\ValueObject'

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
